packages:
  - "packages/*"
  - "examples/*"
  - "sites/*"

catalog:
  react: "19.1.0"
  react-dom: "19.1.0"
  react-server-dom-webpack: "19.1.0"
  typescript: "^5.8.2"
  "@types/react": "^19.0.9"
  "@types/react-dom": "^19.0.3"
  "@types/node": "^22.10.2"
