packages:
  - "packages/*"
  - "examples/*"
  - "sites/*"

catalog:
  react: "19.0.0-rc-e210d081-20240909"
  react-dom: "19.0.0-rc-e210d081-20240909"
  react-server-dom-webpack: "19.0.0-rc-e210d081-20240909"
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  eslint: "^8.57.0"
