packages:
  - packages/*
  - examples/*
  - sites/*

catalog:
  "@types/node": ^22.16.5
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  esbuild: 0.25.8
  react: 19.1.0
  react-dom: 19.1.0
  react-server-dom-webpack: 19.1.0
  typescript: ^5.8.3

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
