packages:
  - "packages/*"
  - "examples/*"
  - "sites/*"

catalog:
  react: "19.0.0-rc-69d4b800-20241021"
  react-dom: "19.0.0-rc-69d4b800-20241021"
  react-server-dom-webpack: "19.0.0-rc-69d4b800-20241021"
  typescript: "^5.6.3"
  "@types/react": "^18.3.12"
  "@types/react-dom": "^18.3.1"
  "@types/node": "^22.8.6"
