packages:
  - packages/*
  - examples/*
  - sites/*

catalog:
  "@types/node": ^22.16.5
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  esbuild: 0.27.2
  react: 19.2.4
  react-dom: 19.2.4
  react-server-dom-webpack: 19.2.4
  typescript: ^5.9.3

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
